experiment_name: rf_aef_v1
save_path: experiments/${experiment_name}

paths:
  report: ${save_path}/${experiment_name}_report.txt
  model: ${save_path}/${experiment_name}_model.pkl

data:
  forest: data/aef/2024/embeddings/forest_2024.parquet
  non_forest: data/aef/2024/embeddings/non_forest_2024.parquet

split:
  shuffle: true
  random_state: 42
  test_size: 0.3
