experiment_name: rf_aef_v1
save_path: experiments/${experiment_name}


paths:
  report: ${save_path}/${experiment_name}_report.txt
  model: ${save_path}/${experiment_name}_model.pkl

data: {}

background_class: 5

split:
  shuffle: true
  random_state: 42
  test_size: 0.3

model:
  n_estimators: 100
  n_jobs: -1

downsample: true